import type { ComboboxOption } from './forge/Combobox'

/**
 * The regions this account can deploy to. Two of them are unavailable, and the
 * label says so — a disabled row must not read as disabled by colour alone.
 */
export const REGIONS: readonly ComboboxOption[] = [
  { value: 'us-east-1', label: 'us-east-1 (N. Virginia)' },
  { value: 'us-east-2', label: 'us-east-2 (Ohio)' },
  { value: 'us-west-1', label: 'us-west-1 (N. California)' },
  { value: 'us-west-2', label: 'us-west-2 (Oregon)' },
  { value: 'ca-central-1', label: 'ca-central-1 (Montreal)' },
  { value: 'ca-west-1', label: 'ca-west-1 (Calgary)' },
  { value: 'mx-central-1', label: 'mx-central-1 (Mexico City)' },
  { value: 'sa-east-1', label: 'sa-east-1 (Sao Paulo)' },
  { value: 'sa-south-1', label: 'sa-south-1 (Santiago)' },
  { value: 'eu-west-1', label: 'eu-west-1 (Ireland)' },
  { value: 'eu-west-2', label: 'eu-west-2 (London)' },
  { value: 'eu-west-3', label: 'eu-west-3 (Paris)' },
  { value: 'eu-central-1', label: 'eu-central-1 (Frankfurt)' },
  { value: 'eu-central-2', label: 'eu-central-2 (Zurich)' },
  { value: 'eu-north-1', label: 'eu-north-1 (Stockholm)' },
  { value: 'eu-south-1', label: 'eu-south-1 (Milan)' },
  { value: 'eu-south-2', label: 'eu-south-2 (Madrid)' },
  { value: 'uk-south-1', label: 'uk-south-1 (Manchester)' },
  { value: 'il-central-1', label: 'il-central-1 (Tel Aviv)' },
  {
    value: 'me-south-1',
    label: 'me-south-1 (Bahrain) — unavailable',
    disabled: true,
  },
  { value: 'me-central-1', label: 'me-central-1 (Dubai)' },
  { value: 'af-south-1', label: 'af-south-1 (Cape Town)' },
  { value: 'af-north-1', label: 'af-north-1 (Cairo)' },
  { value: 'ap-south-1', label: 'ap-south-1 (Mumbai)' },
  { value: 'ap-south-2', label: 'ap-south-2 (Hyderabad)' },
  { value: 'ap-southeast-1', label: 'ap-southeast-1 (Singapore)' },
  { value: 'ap-southeast-2', label: 'ap-southeast-2 (Sydney)' },
  { value: 'ap-southeast-3', label: 'ap-southeast-3 (Jakarta)' },
  { value: 'ap-southeast-4', label: 'ap-southeast-4 (Melbourne)' },
  { value: 'ap-southeast-5', label: 'ap-southeast-5 (Kuala Lumpur)' },
  { value: 'ap-southeast-6', label: 'ap-southeast-6 (Auckland)' },
  { value: 'ap-northeast-1', label: 'ap-northeast-1 (Tokyo)' },
  { value: 'ap-northeast-2', label: 'ap-northeast-2 (Seoul)' },
  { value: 'ap-northeast-3', label: 'ap-northeast-3 (Osaka)' },
  { value: 'ap-east-1', label: 'ap-east-1 (Hong Kong)' },
  { value: 'ap-east-2', label: 'ap-east-2 (Taipei)' },
  {
    value: 'cn-north-1',
    label: 'cn-north-1 (Beijing) — unavailable',
    disabled: true,
  },
  { value: 'cn-northwest-1', label: 'cn-northwest-1 (Ningxia)' },
  { value: 'us-gov-east-1', label: 'us-gov-east-1 (US-Gov East)' },
  { value: 'us-gov-west-1', label: 'us-gov-west-1 (US-Gov West)' },
]
