//! The registry, written out as JSON for the generators that cannot read
//! Rust.
//!
//! The web kit's kind union, starter constructors, slash palette and emoji
//! table are generated by Node scripts under `scripts/generate/`, and `just
//! check` runs them with no Rust toolchain at all. So the crossing point is a
//! committed file: this module renders it, `src/bin/dump-contract.rs` writes
//! it, and `tests/export.rs` fails while the committed copy is stale.
//!
//! Nothing here is part of the editing model. It exists so that
//! [`crate::KINDS`] and [`crate::EMOJI`] have exactly one author.

use serde_json::{json, Value};

use crate::emoji::EMOJI;
use crate::registry::{MarkdownForm, PaletteAction, KINDS};

/// Where the rendered registry belongs, relative to the repository root.
pub const REGISTRY_PATH: &str = "contract/blocks-registry.json";

/// Where the rendered emoji table belongs, relative to the repository root.
pub const EMOJI_PATH: &str = "contract/emoji.json";

/// The placeholder a block id becomes: a starter payload is a template, and
/// the generated constructor mints a fresh id wherever this appears.
pub const ID_PLACEHOLDER: &str = "$id";

/// The registry as JSON: every kind with its wire shape and starter, then the
/// slash palette in the order a kit lists it.
pub fn registry_json() -> String {
    let kinds: Vec<Value> = KINDS
        .iter()
        .map(|entry| {
            let fields: Vec<Value> = entry
                .fields
                .iter()
                .map(|f| json!({ "name": f.name, "ts": f.ts, "optional": f.optional }))
                .collect();
            json!({
                "type": entry.type_name,
                "label": entry.label,
                "is_data": entry.is_data,
                "markdown": markdown_form(entry.markdown),
                "doc": entry.doc,
                "fields": fields,
                "starter": starter_json(&(entry.starter)()),
            })
        })
        .collect();

    let palette: Vec<Value> = crate::registry::palette_rows()
        .into_iter()
        .map(|row| {
            let mut out = json!({ "id": row.id, "label": row.label, "hint": row.hint });
            let obj = out.as_object_mut().expect("a row is an object");
            match row.action {
                PaletteAction::Insert(make) => {
                    obj.insert("insert".into(), starter_json(&make()));
                }
                PaletteAction::WrapColumns(n) => {
                    obj.insert("wrap_columns".into(), json!(n));
                }
            }
            out
        })
        .collect();

    pretty(&json!({
        "generated_from": "crates/forge-blocks/src/registry.rs",
        "kinds": kinds,
        "palette": palette,
    }))
}

/// The emoji table as JSON: `[shortcode, glyph]` pairs, in the table's own
/// sorted order. A list rather than an object, because an object would let a
/// reader's JSON library reorder the pairs and the order is the table's index.
///
/// One pair per line, rather than the pretty printer's four, so that a diff of
/// eight hundred entries reads as one line per changed emoji.
pub fn emoji_json() -> String {
    let pairs: Vec<String> = EMOJI
        .iter()
        .map(|(code, glyph)| format!("    [{}, {}]", string(code), string(glyph)))
        .collect();
    format!(
        "{{\n  \"generated_from\": {},\n  \"emoji\": [\n{}\n  ]\n}}\n",
        string("crates/forge-blocks/src/emoji.rs"),
        pairs.join(",\n")
    )
}

/// One JSON string, escaped as serde would escape it.
fn string(text: &str) -> String {
    serde_json::to_string(text).expect("a string serializes")
}

/// Two-space JSON with the trailing newline every file in the tree ends with.
fn pretty(value: &Value) -> String {
    let mut out = serde_json::to_string_pretty(value).expect("the dump holds no non-string keys");
    out.push('\n');
    out
}

/// The wire name of a markdown form. Kebab-case, because the generators read
/// it as a tag rather than as prose.
fn markdown_form(form: MarkdownForm) -> &'static str {
    match form {
        MarkdownForm::Native => "native",
        MarkdownForm::NativeOrFence => "native-or-fence",
        MarkdownForm::Fence => "fence",
        MarkdownForm::CustomFence => "custom-fence",
        MarkdownForm::Flattened => "flattened",
    }
}

/// A starter payload, with every nested block id replaced by
/// [`ID_PLACEHOLDER`]. A starter that holds blocks (only `columns` does
/// today) mints ids when it runs, and those ids must not reach a committed
/// file — the generated constructor mints its own.
fn starter_json(kind: &crate::BlockKind) -> Value {
    let mut value = serde_json::to_value(kind).expect("a block kind serializes");
    blank_ids(&mut value);
    value
}

/// Replace the `id` of every nested block, in place. A block is an object
/// carrying both an `id` and a registered `type`; the other `id` fields in
/// the schema — a diagram node, a sequence participant, a state — carry no
/// `type` and keep their authored values.
fn blank_ids(value: &mut Value) {
    match value {
        Value::Object(map) => {
            let is_block = map.contains_key("id")
                && map
                    .get("type")
                    .and_then(Value::as_str)
                    .is_some_and(|name| crate::kind_entry(name).is_some());
            if is_block {
                map.insert("id".into(), json!(ID_PLACEHOLDER));
            }
            for child in map.values_mut() {
                blank_ids(child);
            }
        }
        Value::Array(items) => items.iter_mut().for_each(blank_ids),
        _ => {}
    }
}
